import {DefaultTheme, MD3DarkTheme} from "react-native-paper";

export const materialYouTheme = {
        ...DefaultTheme,
        colors: {
            ...DefaultTheme.colors,
            "primary": "#546524",
            "surfaceTint": "#546524",
            "onPrimary": "#FFFFFF",
            "primaryContainer": "#D6EB9B",
            "onPrimaryContainer": "#161F00",
            "secondary": "#5B6147",
            "onSecondary": "#FFFFFF",
            "secondaryContainer": "#DFE6C4",
            "onSecondaryContainer": "#181E09",
            "tertiary": "#39665F",
            "onTertiary": "#FFFFFF",
            "tertiaryContainer": "#BCECE2",
            "onTertiaryContainer": "#00201C",
            "error": "#BA1A1A",
            "onError": "#FFFFFF",
            "errorContainer": "#FFDAD6",
            "onErrorContainer": "#410002",
            "background": "#FAFAEE",
            "onBackground": "#1B1C15",
            "surface": "#FAFAEE",
            "onSurface": "#1B1C15",
            "surfaceVariant": "#E3E4D3",
            "onSurfaceVariant": "#46483C",
            "outline": "#76786B",
            "outlineVariant": "#C6C8B8",
            "shadow": "#000000",
            "scrim": "#000000",
            "inverseSurface": "#303129",
            "inverseOnSurface": "#F2F1E5",
            "inversePrimary": "#BBCF82",
            "primaryFixed": "#D6EB9B",
            "onPrimaryFixed": "#161F00",
            "primaryFixedDim": "#BBCF82",
            "onPrimaryFixedVariant": "#3D4C0D",
            "secondaryFixed": "#DFE6C4",
            "onSecondaryFixed": "#181E09",
            "secondaryFixedDim": "#C3CAA9",
            "onSecondaryFixedVariant": "#434931",
            "tertiaryFixed": "#BCECE2",
            "onTertiaryFixed": "#00201C",
            "tertiaryFixedDim": "#A1D0C6",
            "onTertiaryFixedVariant": "#204E47",
            "surfaceDim": "#DBDBCF",
            "surfaceBright": "#FAFAEE",
            "surfaceContainerLowest": "#FFFFFF",
            "surfaceContainerLow": "#F5F4E8",
            "surfaceContainer": "#EFEEE2",
            "surfaceContainerHigh": "#E9E9DD",
            "surfaceContainerHighest": "#E3E3D7",
    },
};

export const darkTheme = {
    ...MD3DarkTheme,
    colors: {
        ...MD3DarkTheme.colors,
        "primary": "#BBCF82",
        "surfaceTint": "#BBCF82",
        "onPrimary": "#283500",
        "primaryContainer": "#3D4C0D",
        "onPrimaryContainer": "#D6EB9B",
        "secondary": "#C3CAA9",
        "onSecondary": "#2D331C",
        "secondaryContainer": "#434931",
        "onSecondaryContainer": "#DFE6C4",
        "tertiary": "#A1D0C6",
        "onTertiary": "#023731",
        "tertiaryContainer": "#204E47",
        "onTertiaryContainer": "#BCECE2",
        "error": "#FFB4AB",
        "onError": "#690005",
        "errorContainer": "#93000A",
        "onErrorContainer": "#FFDAD6",
        "background": "#12140D",
        "onBackground": "#E3E3D7",
        "surface": "#12140D",
        "onSurface": "#E3E3D7",
        "surfaceVariant": "#46483C",
        "onSurfaceVariant": "#C6C8B8",
        "outline": "#909284",
        "outlineVariant": "#46483C",
        "shadow": "#000000",
        "scrim": "#000000",
        "inverseSurface": "#E3E3D7",
        "inverseOnSurface": "#303129",
        "inversePrimary": "#546524",
        "primaryFixed": "#D6EB9B",
        "onPrimaryFixed": "#161F00",
        "primaryFixedDim": "#BBCF82",
        "onPrimaryFixedVariant": "#3D4C0D",
        "secondaryFixed": "#DFE6C4",
        "onSecondaryFixed": "#181E09",
        "secondaryFixedDim": "#C3CAA9",
        "onSecondaryFixedVariant": "#434931",
        "tertiaryFixed": "#BCECE2",
        "onTertiaryFixed": "#00201C",
        "tertiaryFixedDim": "#A1D0C6",
        "onTertiaryFixedVariant": "#204E47",
        "surfaceDim": "#12140D",
        "surfaceBright": "#383A32",
        "surfaceContainerLowest": "#0D0F08",
        "surfaceContainerLow": "#1B1C15",
        "surfaceContainer": "#1F2019",
        "surfaceContainerHigh": "#292B23",
        "surfaceContainerHighest": "#34362D"
    },
};
